src/main/java/unidue/ubo/ldap/picker/LDAPPIDSearch.java, src/main/java/unidue/ubo/ldap/picker/LDAPService.java, src/main/java/unidue/ubo/matcher/MCRUserMatcherLDAP.java, src/main/java/unidue/ubo/matcher/MCRUserMatcherLocal.java, src/main/java/unidue/ubo/matcher/MCRUserMatcherUtils.java, src/main/java/unidue/ubo/picker/IdentityResolver.java, src/main/java/unidue/ubo/publication/PublicationEventHandler.java, src/main/resources/messages_de.properties, src/main/resources/messages_en.properties, src/main/resources/xsl/ldappidsearch.xsl
https://mycore.atlassian.net/browse/UBO-11
=> UBO-11 - Ldap picker strategy improvements

src/main/java/unidue/ubo/publication/PublicationEventHandler.java, src/main/resources/xsl/list-wizard.xsl, src/main/resources/xsl/mods-display.xsl, src/main/setup/solr/schema.xml, src/main/webapp/import-editor.xed, src/main/webapp/js/author_search.js, src/main/webapp/list-wizard.xed
- schema.xml was changed, need to restart/reload solr
- changes only affect newly imported publications, "rebuild metadata search of type..." does NOT work
- new mycore.properties config: 
MCR.user2.matching.publication.connection.strategy=uuid
=> Ubo 36 ubo 37 lead id in mcr user reworked publicationlist

src/main/resources/mycore.properties
=> UBO-52 use k10+ unapi interface for ppn import

ubo-common/src/main/resources/xsl/user.xsl
https://mycore.atlassian.net/browse/UBO-79
=> UBO-79 step handling for user servlet missing

ubo-common/src/main/java/org/mycore/ubo/DozBibCommands.java, ubo-common/src/main/java/org/mycore/ubo/importer/scopus/PaginatedScopusQuery.java, ubo-common/src/main/java/org/mycore/ubo/importer/scopus/ScopusUpdater.java
https://mycore.atlassian.net/jira/software/c/projects/UBO/issues/UBO-95
=> UBO-95 Allow Scopus Import using flexible query

ubo-common/src/main/vue/author_search/src/App.vue
https://mycore.atlassian.net/jira/software/c/projects/UBO/issues/UBO-88
=> UBO-88 Can't remove lead id via IdentityPicker

ubo-common/src/main/java/org/mycore/ubo/resources/UBOExportResource.java, ubo-common/src/main/resources/config/ubo-common/mycore.properties, ubo-common/src/main/resources/xsl/solr2csv.xsl, ubo-common/src/main/vue/publication_list/src/App.vue
Test this together with https://github.com/MyCoRe-Org/mycore/pull/1307
=> UBO-100 Export has wrong file extension

ubo-webapp/pom.xml
=> Change SOLR mirror URL to archive.apache.org

ubo-common/src/main/resources/config/ubo-common/mycore.properties
Man sollte nur UBO.projectid.default ändern müssen und die Änderung sollte sich dann auf die anderen Stellen durchschlagen.
=> reuse property value of UBO.projectid.default

ubo-common/src/main/resources/xsl/mods-filter-supported.xsl
- also identifier of type dbt and uri
- do also filter notes with other type than allowed list
=> add typeOfResource to allowed fields

ubo-common/src/main/java/org/mycore/ubo/resources/UBOExportResource.java, ubo-common/src/main/resources/config/ubo-common/mycore.properties, ubo-common/src/main/resources/xsl/ubo-solr.xsl
[Link to Jira](https://mycore.atlassian.net/browse/UBO-109)
Tested here:
https://bibliografie.th-koeln.de/servlets/solr/select2?q=%2Bstatus%3Aconfirmed+%2Byear%3A%5B2021+TO+*%5D+%2B%7B%21parent+which%3D%22objectType%3Amods%22+filters%3D%24childfq%7DobjectKind%3Aname&childfq=%2Bname_id_connection%3A%28a697ca7f-fff2-4abc-a4aa-8115256d8126%29+%2Brole%3A%28aut.top+OR+cre.top+OR+tch.top+OR+pht.top+OR+prg.top+OR+edt.top%29&rows=9999&sort=year+asc&XSL.Transformer=response-csl-html&XSL.style=technische-universitat-dresden-linguistik
vs.
https://bibliografie.th-koeln.de/servlets/solr/select2?q=%2Bstatus%3Aconfirmed+%2Byear%3A%5B2021+TO+*%5D+%2B%7B%21parent+which%3D%22objectType%3Amods%22+filters%3D%24childfq%7DobjectKind%3Aname&childfq=%2Bname_id_connection%3A%28a697ca7f-fff2-4abc-a4aa-8115256d8126 …
=> UBO-109 - Fix join query and person index

ubo-cli/pom.xml, ubo-webapp/pom.xml
[UBO-145](https://mycore.atlassian.net/browse/UBO-145)
=> UBO-145 add mycore-ocfl as runtime dependency

ubo-common/src/main/resources/META-INF/resources/import-editor.xed
- colons with right whitespace
- mandatory as css class
=> layout improvements:

ubo-common/src/main/resources/xsl/mods-display.xsl
[Ticket in ThUniBib](https://github.com/ThULB/ThUniBib/issues/142)
=> 142 Support marcrelator_corporation from ThUniBib

ubo-common/src/main/resources/config/ubo-common/solr/main/solr-schema.json, ubo-common/src/main/resources/xsl/ubo-solr.xsl
Index mods:note[@type='intern'] to separate field
https://github.com/ThULB/ThUniBib/issues/202
=> UBO-195 Index mods:note[@type='intern'] to separate field

ubo-common/src/main/resources/xsl/ubo-solr.xsl
Index mods:note[@type='intern'] to separate field - revisited
=> Index mods:note[@type='intern'] to separate field

ubo-common/src/main/resources/xsl/mods-display.xsl
... mods collections such as export lists
=> UBO-209 fix xpath for dateIssued, old version matches other mods in

ubo-common/src/main/resources/config/ubo-common/mycore.properties, ubo-common/src/main/resources/xsl/mods-display.xsl
needed by https://github.com/ThULB/ThUniBib/issues/248
=> UBO-211 Allow to linked catalog in mods-display.xsl to be customizable

ubo-common/src/main/resources/config/ubo-common/solr/main/solr-schema.json, ubo-common/src/main/resources/xsl/ubo-solr.xsl
needed by https://github.com/ThULB/ThUniBib/issues/258
=> UBO-213 Index solr field 'licence'

ubo-common/src/main/resources/config/ubo-common/solr/main/solr-config.json
[Jira-Ticket](https://mycore.atlassian.net/browse/UBO-232)
=> UBO-232 fix navigation with select2

ubo-common/src/main/resources/META-INF/resources/user-editor-customization.xed
[UBO-277](https://mycore.atlassian.net/jira/software/c/projects/UBO/issues/UBO-277)
[UBO-277]: https://mycore.atlassian.net/browse/UBO-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-277 Removed @min="4" from repeat element

ubo-common/src/main/java/org/mycore/ubo/importer/orcid/Orcid2WorksTransformer.java
[UBO-281 ](https://mycore.atlassian.net/jira/software/c/projects/UBO/issues/UBO-281)
=> UBO-281 Fixed import of works from ORCID

ubo-common/src/main/resources/META-INF/resources/scss/_ubo-common.scss, ubo-common/src/main/resources/xsl/mods-display.xsl
https://jira.gbv.de/browse/DMS-300
=> DMS-300 adds a better way to show authors without floating

ubo-common/src/main/java/org/mycore/ubo/publication/PublicationEventHandler.java
[JIRA: UBO-293](https://mycore.atlassian.net/browse/UBO-293)
=> UBO-293 FSU040THUL-2186 Fixed generated heading for local users to "family name, given name"

ubo-common/src/main/resources/xsl/ubo-solr.xsl
[JIRA: UBO-296](https://mycore.atlassian.net/browse/UBO-296)
=> UBO-296 Made indexing of year independent of actual position of the mods:originInfo/mods:dateIssued element

ubo-common/src/main/java/org/mycore/ubo/ldap/picker/LDAPWithLocalService.java
[JIRA: UBO-300](https://mycore.atlassian.net/browse/UBO-300)
=> UBO-300 Flip parts of name in PersonResult list

ubo-common/src/main/resources/xsl/response-facets.xsl, ubo-common/src/main/resources/xsl/response-get-handler.xsl
[Link to JIRA](https://mycore.atlassian.net/browse/UBO-305)
please see https://github.com/ThULB/ThUniBib/pull/485 for context
=> UBO-305 Allow to configure solr request handlers in response-facets.xsl

ubo-common/src/main/resources/xsl/mods-display.xsl
[UBO-307](https://mycore.atlassian.net/browse/UBO-307)
[UBO-307]: https://mycore.atlassian.net/browse/UBO-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-307 FSU040THUL-2605 Added text-wrap class to .personalName elements

ubo-common/src/main/java/org/mycore/ubo/DozBibCommands.java, ubo-common/src/main/resources/xsl/mods-postprocessor.xsl, ubo-common/src/main/resources/xsl/mods-preprocessor.xsl
[UBO-310](https://mycore.atlassian.net/browse/UBO-310)
[UBO-310]: https://mycore.atlassian.net/browse/UBO-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-310 FSU040THUL-2479 Import via list and newPublication.xed produce different mods:identifier[@type='uri'] elements

ubo-common/src/main/resources/xsl/mods-display.xsl
[UBO-311](https://mycore.atlassian.net/browse/UBO-311)
[UBO-311]: https://mycore.atlassian.net/browse/UBO-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-311 FSU040-THUL-2889 The query parts in the links of the origin badges are not quoted properly

ubo-common/src/main/resources/xsl/response-get-handler.xsl, ubo-common/src/main/resources/xsl/response.xsl
[UBO-316](https://mycore.atlassian.net/browse/UBO-316)
[UBO-316]: https://mycore.atlassian.net/browse/UBO-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-316 Made request handler for statistics configurable

ubo-common/src/main/java/org/mycore/ubo/basket/Results2Basket.java, ubo-common/src/main/resources/xsl/response.xsl
[UBO-318](https://mycore.atlassian.net/browse/UBO-318)
[UBO-318]: https://mycore.atlassian.net/browse/UBO-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-318 Read request handler from $RequestURL

ubo-common/src/main/resources/config/ubo-common/messages_de.properties, ubo-common/src/main/resources/config/ubo-common/messages_en.properties, ubo-common/src/main/resources/xsl/response.xsl
[UBO-317](https://mycore.atlassian.net/browse/UBO-317)
[UBO-317]: https://mycore.atlassian.net/browse/UBO-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-317 Add button to copy url to result set to clipboard

ubo-common/src/main/resources/config/ubo-common/mycore.properties
[UBO-320](https://mycore.atlassian.net/browse/UBO-320)
[UBO-320]: https://mycore.atlassian.net/browse/UBO-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-320 Ugrade MCR.user2.LDAP.Mapping.labeledURI.id_gnd.schema to https

ubo-common/src/main/resources/xsl/user.xsl
[UBO-322](https://mycore.atlassian.net/browse/UBO-322)
[UBO-322]: https://mycore.atlassian.net/browse/UBO-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-322 Display realname (if any) rather than uid of user on profile page

ubo-common/src/main/resources/config/ubo-common/solr/main/solr-schema.json, ubo-common/src/main/resources/xsl/ubo-solr.xsl
[UBO-323](https://mycore.atlassian.net/browse/UBO-323)
[UBO-323]: https://mycore.atlassian.net/browse/UBO-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-323 Index corresponding author

ubo-common/src/main/resources/xsl/response.xsl, ubo-common/src/main/resources/xsl/ubo-dialog.xsl
[UBO-324](https://mycore.atlassian.net/browse/UBO-324)
[UBO-324]: https://mycore.atlassian.net/browse/UBO-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-324 Made generated id's in ubo-dialog.xsl unique

pom.xml, ubo-common/pom.xml, ubo-common/src/main/java/org/mycore/ubo/ratelimit/MCRRateLimitBuckets.java, ubo-common/src/main/java/org/mycore/ubo/ratelimit/MCRRateLimitResolver.java, ubo-common/src/main/resources/config/ubo-common/mycore.properties, ubo-common/src/test/java/org/mycore/ubo/ratelimit/MCRRateLimitResolverTest.java
[Link to jira](https://mycore.atlassian.net/browse/UBO-309).
=> UBO-309 Add rate-limiting URI-Resolver

ubo-common/src/main/java/org/mycore/ubo/DozBibCommands.java, ubo-common/src/main/resources/config/ubo-common/messages_de.properties, ubo-common/src/main/resources/config/ubo-common/messages_en.properties, ubo-common/src/main/resources/xsl/response-facets.xsl, ubo-common/src/main/resources/xsl/response.xsl, ubo-common/src/main/resources/xsl/statistics.xsl
[UBO-325](https://mycore.atlassian.net/browse/UBO-325)
[UBO-325]: https://mycore.atlassian.net/browse/UBO-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-325 Improve accessibility of result page

ubo-common/src/main/java/org/mycore/ubo/ldap/picker/LDAPService.java, ubo-common/src/main/vue/author_search/src/components/PersonSearchResult.vue
[UBO-321](https://mycore.atlassian.net/browse/UBO-321)
[UBO-321]: https://mycore.atlassian.net/browse/UBO-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-321 Do not display placeholders in identity picker search result

ubo-common/src/main/resources/xsl/html-layout-backend.xsl
[UBO-328](https://mycore.atlassian.net/browse/UBO-328)
[UBO-328]: https://mycore.atlassian.net/browse/UBO-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-328 Allow to provide dropdown dividers in user menu via navigation.xml

ubo-common/src/main/java/org/mycore/ubo/publication/PublicationEventHandler.java
[UBO-330](https://mycore.atlassian.net/browse/UBO-330)
[UBO-330]: https://mycore.atlassian.net/browse/UBO-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-330 Fixed NPE in PublicationEventHandler

ubo-common/src/main/java/org/mycore/mods/enrichment/EnrichmentCommands.java, ubo-common/src/main/resources/config/ubo-common/mycore.properties
see https://mycore.atlassian.net/browse/UBO-331
=> UBO-331 add new enrichment command in new command group

ubo-common/src/main/resources/config/ubo-common/messages_de.properties, ubo-common/src/main/resources/config/ubo-common/messages_en.properties, ubo-common/src/main/resources/xsl/response.xsl
[UBO-332](https://mycore.atlassian.net/browse/UBO-332)
[UBO-332]: https://mycore.atlassian.net/browse/UBO-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-332 Added missing tooltip for statistics button

ubo-common/src/main/resources/config/ubo-common/solr/main/solr-schema.json, ubo-common/src/main/resources/xsl/ubo-solr.xsl
[UBO-333](https://mycore.atlassian.net/browse/UBO-333)
[UBO-333]: https://mycore.atlassian.net/browse/UBO-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-333 FSU040THUL-3541 Renamed solr fields 'person_aut_corresp*' to 'corresponding_aut*'

ubo-common/src/main/resources/xsl/mods-filter-supported.xsl
[UBO-334](https://mycore.atlassian.net/browse/UBO-334)
[UBO-334]: https://mycore.atlassian.net/browse/UBO-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-334 Support mods:genre with authorityURI and valueURI

ubo-common/src/main/resources/xsl/mods-dc.xsl
[UBO-339](https://mycore.atlassian.net/browse/UBO-339)
[UBO-339]: https://mycore.atlassian.net/browse/UBO-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-339 Prevent ArrayIndexOutOfBoundException caused in mods-dc.xsl

ubo-common/src/main/resources/xsl/mods-preprocessor.xsl
[UBO-337](https://mycore.atlassian.net/browse/UBO-337)
[UBO-337]: https://mycore.atlassian.net/browse/UBO-337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-337 Do not map mods:classification with generator attribute

ubo-common/src/main/resources/xsl/mods-display.xsl
[UBO-341](https://mycore.atlassian.net/browse/UBO-341)
[UBO-341]: https://mycore.atlassian.net/browse/UBO-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-341 FSU040THUL-3715 Display at least language code when language code cannot be resolved

ubo-common/src/main/resources/xsl/response-facets.xsl
[UBO-342](https://mycore.atlassian.net/browse/UBO-342)
[UBO-342]: https://mycore.atlassian.net/browse/UBO-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-342-FSU040THUL-3861 Fixed non scrolling facet values

ubo-common/src/main/resources/xsl/mods-display.xsl
[UBO-344](https://mycore.atlassian.net/browse/UBO-344)
[UBO-344]: https://mycore.atlassian.net/browse/UBO-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-344 Fixed url for genre link badge

ubo-common/src/main/java/org/mycore/ubo/local/LocalService.java
[UBO-345](https://mycore.atlassian.net/browse/UBO-345)
[UBO-345]: https://mycore.atlassian.net/browse/UBO-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-345 Do not die on multiple LEAD_ID in IdentityPicker

ubo-common/src/main/java/org/mycore/ubo/importer/ImportJob.java, ubo-common/src/main/java/org/mycore/ubo/importer/ImportListJobAction.java
[UBO-347](https://mycore.atlassian.net/browse/UBO-347)
[UBO-347]: https://mycore.atlassian.net/browse/UBO-347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-347 Let ImportListJobAction not use ImportJob.saveAndIndex()

README.md, docker-entrypoint.sh, ubo-common/src/main/resources/META-INF/resources/edit-admin.xed, ubo-common/src/main/resources/META-INF/resources/edit-publication.xed, ubo-common/src/main/resources/META-INF/resources/import-editor.xed, ubo-common/src/main/resources/META-INF/resources/js/language-search.js, ubo-common/src/main/resources/config/ubo-common/messages_de.properties, ubo-common/src/main/resources/config/ubo-common/messages_en.properties
To add the right permissions you need to add run `bin/ubo.sh update permission read for id restapi:/classifications with rulefile ubo-cli/src/main/setup/acl/acl-rule-always-allowed.xml described by always allowed` or add `read restapi:/classifications always allowed`
=> UBO-348 large rfc5646 classification makes editor slow

pom.xml
[UBO-350](https://mycore.atlassian.net/browse/UBO-350)
[UBO-350]: https://mycore.atlassian.net/browse/UBO-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-350 Set pica2mods version to 2.10

ubo-cli/src/main/setup/classifications/ORIGIN.xml, ubo-cli/src/main/setup/classifications/destatis.xml, ubo-common/src/main/resources/config/ubo-common/mycore.properties, ubo-common/src/main/resources/config/ubo-common/solr/main/solr-schema.json, ubo-common/src/main/resources/xsl/ubo-solr.xsl
we can use classification mapping to include destatis information into mods based on information in origin classification; this is related to UBO-245 and should be checked therefore
=> enable classification mapping for destatis classification

ubo-common/src/main/resources/META-INF/resources/js/language-search.js
[UBO-359](https://mycore.atlassian.net/browse/UBO-359)
[UBO-359]: https://mycore.atlassian.net/browse/UBO-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-359 FSU040THUL-4433 Remove parent div once it has been processed

ubo-common/src/main/java/org/mycore/ubo/relations/ParentChildRelationChecker.java
[UBO-358](https://mycore.atlassian.net/browse/UBO-358)
[UBO-358]: https://mycore.atlassian.net/browse/UBO-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-358 FSU040THUL-3822 Do not throw exception when object has both parent and multiple children

ubo-common/src/main/java/org/mycore/ubo/ldap/LDAPAuthenticator.java, ubo-common/src/main/java/org/mycore/ubo/matcher/MCRUserMatcherLDAP.java
[UBO-363](https://mycore.atlassian.net/browse/UBO-363)
[UBO-363]: https://mycore.atlassian.net/browse/UBO-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-363 Fixed NullPointerException in MCRUserMatcherLDAP

ubo-common/src/main/resources/config/ubo-common/mycore.properties, ubo-common/src/main/resources/xslt/solr2csv.xsl
[UBO-367](https://mycore.atlassian.net/browse/UBO-367)
[UBO-367]: https://mycore.atlassian.net/browse/UBO-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-367 FSU040THUL-5319 Fixed CSV export

ubo-common/src/main/resources/xsl/response-facets.xsl
[UBO-368](https://mycore.atlassian.net/browse/UBO-368)
[UBO-368]: https://mycore.atlassian.net/browse/UBO-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-369 Support resolving of values of destatis category id's in response-facets.xsl

ubo-common/src/main/resources/xsl/mods-display.xsl
[UBO-381](https://mycore.atlassian.net/browse/UBO-381)
[UBO-381]: https://mycore.atlassian.net/browse/UBO-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-381 Added leading brace to role when role is interviewer

ubo-common/src/main/java/org/mycore/ubo/importer/scopus/ScopusImporter.java, ubo-common/src/main/resources/config/ubo-common/mycore.properties, ubo-common/src/main/resources/xsl/rss-import-e-mail.xsl
[UBO-382](https://mycore.atlassian.net/browse/UBO-382)
[UBO-382]: https://mycore.atlassian.net/browse/UBO-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-382 Allow to set preconfigured classification values during scopus import

ubo-common/src/main/resources/config/ubo-common/solr/main/solr-schema.json, ubo-common/src/main/resources/xsl/ubo-solr.xsl
[Jira Issue](https://mycore.atlassian.net/browse/UBO-388).
=> UBO-388: New field aeplus_lsf

ubo-common/src/main/resources/xsl/mods-display.xsl
[UBO-395](https://mycore.atlassian.net/browse/UBO-395)
[UBO-395]: https://mycore.atlassian.net/browse/UBO-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-395 FSU040THUL-7054 Ignore date of journal in cite view

docker-entrypoint.sh, ubo-common/pom.xml
[UBO-404](https://mycore.atlassian.net/browse/UBO-404)
[UBO-404]: https://mycore.atlassian.net/browse/UBO-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-404 Added dependency to HikariCP to allow connection pooling

ubo-common/src/main/java/org/mycore/ubo/dedup/jpa/DeduplicationNoDuplicate.java
[UBO-405](https://mycore.atlassian.net/browse/UBO-405)
[UBO-405]: https://mycore.atlassian.net/browse/UBO-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-405 DeduplicationNoDuplicate should support usernames with more than 32 characters

ubo-common/src/main/java/org/mycore/ubo/matcher/MCRUserMatcherUtils.java
[UBO-406](https://mycore.atlassian.net/browse/UBO-406)
[UBO-406]: https://mycore.atlassian.net/browse/UBO-406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-406 Replace + sign with %20 after encoding by URLEncoder

ubo-common/src/main/java/org/mycore/ubo/importer/ImportIdProvider.java, ubo-common/src/main/java/org/mycore/ubo/importer/ImportJob.java, ubo-common/src/main/java/org/mycore/ubo/importer/ListImportIdprovider.java, ubo-common/src/main/java/org/mycore/ubo/importer/ListImportJob.java, ubo-common/src/main/java/org/mycore/ubo/importer/scopus/ScopusImportIdProvider.java, ubo-common/src/main/java/org/mycore/ubo/importer/scopus/ScopusImporter.java, ubo-common/src/main/resources/config/ubo-common/mycore.properties
[UBO-408](https://mycore.atlassian.net/browse/UBO-408)
[UBO-408]: https://mycore.atlassian.net/browse/UBO-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-408 Allow to customize import id of list and scopus imports

pom.xml
[UBO-420](https://mycore.atlassian.net/browse/UBO-420)
[UBO-420]: https://mycore.atlassian.net/browse/UBO-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-420 Set pica2mods to version 2.12

ubo-common/src/main/java/org/mycore/ubo/importer/scopus/ScopusImporter.java, ubo-common/src/main/resources/config/ubo-common/mycore.properties
tested locally, should work as expected.
=> UBO-421 a way to configure always send for scopus importer

ubo-common/src/main/java/org/mycore/ubo/importer/ImportListJobAction.java
[UBO-423](https://mycore.atlassian.net/browse/UBO-423)
[UBO-423]: https://mycore.atlassian.net/browse/UBO-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-423 FSU040THUL-8624 Fixed setting genre during async execution of import job

ubo-common/src/main/resources/config/ubo-common/mycore.properties, ubo-common/src/main/resources/xsl/mods-display.xsl
- [UBO-426](https://mycore.atlassian.net/browse/UBO-426)
- needed by https://github.com/ThULB/ThUniBib/pull/782
[UBO-426]: https://mycore.atlassian.net/browse/UBO-426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-426 Allow to hide affiliation marker when person has a connection id but is marked as not affiliated

ubo-common/src/main/resources/xsl/mods-display.xsl
[UBO-432](https://mycore.atlassian.net/browse/UBO-432)
[UBO-432]: https://mycore.atlassian.net/browse/UBO-432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UBO-432 Indicate corresponding author even when author is marked as not affiliated with university
